In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import warnings

warnings.filterwarnings("ignore")

In [2]:
import pandas as pd

customers = pd.read_excel("Synthetic_Ecommerce_Analytics_Dataset.xlsx", sheet_name="customers")

products = pd.read_excel("Synthetic_Ecommerce_Analytics_Dataset.xlsx", sheet_name="products")

sessions = pd.read_excel("Synthetic_Ecommerce_Analytics_Dataset.xlsx", sheet_name="sessions")

events = pd.read_excel("Synthetic_Ecommerce_Analytics_Dataset.xlsx", sheet_name="events")

orders = pd.read_excel("Synthetic_Ecommerce_Analytics_Dataset.xlsx", sheet_name="orders")

order_items = pd.read_excel("Synthetic_Ecommerce_Analytics_Dataset.xlsx", sheet_name="order_items")

payments = pd.read_excel("Synthetic_Ecommerce_Analytics_Dataset.xlsx", sheet_name="payments")

campaigns = pd.read_excel("Synthetic_Ecommerce_Analytics_Dataset.xlsx", sheet_name="campaigns")

In [3]:
customers.head()

   customer_id signup_date  gender  age       city state segment
0            1  2024-01-13  Female   33  Bengaluru    KA     Low
1            2  2024-12-12    Male   55     Mysuru    KA     Low
2            3  2024-02-17    Male   32  Bengaluru    KA    High
3            4  2024-11-28  Female   32       Pune    MH    High
4            5  2024-01-04    Male   45  New Delhi    DL  Medium

In [4]:
customers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   customer_id  500 non-null    int64
 1   signup_date  500 non-null    object
 2   gender       500 non-null    object
 3   age          500 non-null    int64
 4   city         500 non-null    object
 5   state        500 non-null    object
 6   segment      500 non-null    object
dtypes: int64(2), object(5)
memory usage: 27.5+ KB

In [5]:
customers.describe(include='all')

        customer_id signup_date  gender         age       city state segment
count    500.000000         500     500  500.000000        500   500     500
unique          NaN         257       2         NaN          7     5       3
top             NaN  2024-09-15  Female         NaN  Hyderabad    TS    High
freq            NaN           5     260         NaN        118   118     180
mean     250.500000         NaN     NaN   38.876000        NaN   NaN     NaN
std      144.481833         NaN     NaN   12.254181        NaN   NaN     NaN
min        1.000000         NaN     NaN   18.000000        NaN   NaN     NaN
25%      125.750000         NaN     NaN   27.000000        NaN   NaN     NaN
50%      250.500000         NaN     NaN   39.000000        NaN   NaN     NaN
75%      375.250000         NaN     NaN   49.000000        NaN   NaN     NaN
max      500.000000         NaN     NaN   60.000000        NaN   NaN     NaN

In [6]:
customers.shape

(500, 7)

In [7]:
customers.columns

Index(['customer_id', 'signup_date', 'gender', 'age', 'city', 'state',
       'segment'],
      dtype='object')

In [8]:
customers.dtypes

customer_id     int64
signup_date    object
gender         object
age             int64
city           object
state          object
segment        object
dtype: object

In [9]:
customers.isnull().sum()

customer_id    0
signup_date    0
gender         0
age            0
city           0
state          0
segment        0
dtype: int64

In [10]:
customers.duplicated().sum()

np.int64(0)

In [11]:
customers['signup_date'] = pd.to_datetime(customers['signup_date'])

sessions['session_start'] = pd.to_datetime(sessions['session_start'])

events['event_time'] = pd.to_datetime(events['event_time'])

orders['order_date'] = pd.to_datetime(orders['order_date'])

In [12]:
customers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   customer_id  500 non-null    int64
 1   signup_date  500 non-null    datetime64[ns]
 2   gender       500 non-null    object
 3   age          500 non-null    int64
 4   city         500 non-null    object
 5   state        500 non-null    object
 6   segment      500 non-null    object
dtypes: datetime64[ns](1), int64(2), object(4)
memory usage: 27.5+ KB

In [21]:
orders['customer_id'].isin(customers['customer_id']).all()

np.True_

In [22]:
order_items['product_id'].isin(products['product_id']).all()

np.True_

In [23]:
payments['order_id'].isin(orders['order_id']).all()

np.True_

In [24]:
products[['cost_price','selling_price']].describe()

        cost_price  selling_price
count    80.000000      80.000000
mean   1675.525000    2320.239750
std     802.547163    1129.615396
min     133.000000     196.610000
25%    1082.250000    1398.815000
50%    1749.000000    2465.255000
75%    2302.000000    3319.662500
max    2942.000000    4566.190000

In [25]:
(products['selling_price'] < 0).sum()

np.int64(0)

In [26]:
order_items['discount_percent'].describe()

count    631.000000
mean      10.039620
std        7.185083
min        0.000000
25%        5.000000
50%       10.000000
75%       15.000000
max       20.000000
Name: discount_percent, dtype: float64

In [27]:
(products['selling_price'] <
products['cost_price']).sum()

np.int64(0)

In [28]:
events['event_type'].value_counts()

event_type
view           2000
add_to_cart    1176
purchase        631
Name: count, dtype: int64

In [29]:
payments['payment_status'].value_counts()

payment_status
Success    631
Name: count, dtype: int64

In [30]:
!pip install psycopg2-binary sqlalchemy

Requirement already satisfied: psycopg2-binary in c:\users\harshitha\anaconda3\lib\site-packages (2.9.12)
Requirement already satisfied: sqlalchemy in c:\users\harshitha\anaconda3\lib\site-packages (2.0.39)
Requirement already satisfied: greenlet!=0.4.17 in c:\users\harshitha\anaconda3\lib\site-packages (from sqlalchemy) (3.1.1)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\harshitha\anaconda3\lib\site-packages (from sqlalchemy) (4.12.2)

In [32]:
from sqlalchemy import create_engine


username = "postgres"      
password = "password" 
host = "localhost"         
port = "5432"              
database = "ecommerce_data_analysis"    

engine = create_engine(f"postgresql+psycopg2://{username}:{password}@{host}:{port}/{database}")


table_name = "ecommerce"  
customers.to_sql("customers", engine, if_exists="replace", index=False)
products.to_sql("products", engine, if_exists="replace", index=False)
sessions.to_sql("sessions", engine, if_exists="replace", index=False)
events.to_sql("events", engine, if_exists="replace", index=False)
orders.to_sql("orders", engine, if_exists="replace", index=False)
order_items.to_sql("order_items", engine, if_exists="replace", index=False)
payments.to_sql("payments", engine, if_exists="replace", index=False)

print("All tables uploaded successfully!")

All tables uploaded successfully!